// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Zgi5aAgRvL-z-JP7FLRA1748_bl0Tq0',
    appId: '1:453853196321:web:28dae61b01477145dff360',
    messagingSenderId: '453853196321',
    projectId: 'mandarat-e382d',
    authDomain: 'mandarat-e382d.firebaseapp.com',
    storageBucket: 'mandarat-e382d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArECEUVdiQBIuIj2etZpoVN97qSxHTUDk',
    appId: '1:453853196321:android:4c4bced31c63a394dff360',
    messagingSenderId: '453853196321',
    projectId: 'mandarat-e382d',
    storageBucket: 'mandarat-e382d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwChvGP_HZ26fB0pXTCCq0cuDkvtk8Fkw',
    appId: '1:453853196321:ios:016f4798a17a31b6dff360',
    messagingSenderId: '453853196321',
    projectId: 'mandarat-e382d',
    storageBucket: 'mandarat-e382d.appspot.com',
    iosClientId: '453853196321-mtqror6g7k7pauj949h8p0t5do9i9oht.apps.googleusercontent.com',
    iosBundleId: 'com.icedmak.mandarat.mandarat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwChvGP_HZ26fB0pXTCCq0cuDkvtk8Fkw',
    appId: '1:453853196321:ios:016f4798a17a31b6dff360',
    messagingSenderId: '453853196321',
    projectId: 'mandarat-e382d',
    storageBucket: 'mandarat-e382d.appspot.com',
    iosClientId: '453853196321-mtqror6g7k7pauj949h8p0t5do9i9oht.apps.googleusercontent.com',
    iosBundleId: 'com.icedmak.mandarat.mandarat',
  );
}
